#pragma once

#include "sliding-window.h"
#include "tree.h"
#include "greedy/greedy.h"
#include "bitwise/bitwise.h"
#include "backtracking/backtracking.h"
#include "array/arr.h"
#include "string/str.h"
#include "dp.h"
#include "heap.h"
#include "design/design.h"
#include "maths.h"
#include "graph.h"
#include "binary-search.h"
#include "linked-list.h"
